export var SET_PRODUCTS_PER_PAGE = 'SET_PRODUCTS_PER_PAGE';
export const FETCH_PRODUCTS_REQUESTED = 'FETCH_PRODUCTS_REQUESTED';
export const PRODUCTS_FETCHED = 'PRODUCTS_FETCHED';
export const ERROR_OCCURED = 'ERROR_OCCURED';
